'use strict'
@@include('files/regular.js', {})
@@include('files/functions.js', {})
@@include('files/sliders.js', {})
@@include('files/script.js', {})
@@include('files/sorting.js', {})
@@include('files/forms.js', {})
@@include('files/scroll.js', {})
@@include('files/map.js', {})
